OpenMusic/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('tracks.urls')),
    path('account/', include('accounts.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.conf.urls import url
from django.conf.urls.static import static
from django.conf import settings
from django.urls import include
from .views import UserProfileView, UserProfileSearchView, TrackAddView


urlpatterns = [
    url(r'^', include('allauth.urls')),
    url(r'^profile$', UserProfileView.as_view(), name='profile'),
    url(r'^trackadd/$', TrackAddView.as_view(), name='track_add'),
    url(r'^profile/(?P<name>\w+)$', UserProfileSearchView.as_view(), name='profile'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tracks/urls.py
from django.conf.urls import url
from django.conf.urls.static import static
from django.conf import settings
from .views import TrackDetailView, TrackListView, AuthorDetailView, MainView


app_name = 'tracks'

urlpatterns = [
    url(r'^$', MainView.as_view(), name='main'),
    url(r'^tracks/$', TrackListView.as_view(), name='tracks'),
    url(r'^tracks/(?P<name>\w+)$', TrackListView.as_view(), name='tracks'),
    url(r'^track/(?P<slug>[-\w]+)/$', TrackDetailView.as_view(), name='track'),
    url(r'^author/(?P<slug>[-\w]+)/$', AuthorDetailView.as_view(), name='author'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import User


class UserProfile(models.Model):
    User = models.ForeignKey(User, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='accounts/profile/', blank=True)
    description = models.TextField(max_length=3000, blank=True, null=True, default='')

tracks/models.py
from django.contrib.auth.models import User
from django.db.models import Model
from django.db import models
from django.urls import reverse
from autoslug import AutoSlugField


class Author(Model):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    description = models.TextField(max_length=10000, default="...")
    slug = AutoSlugField(db_index=True, populate_from='last_name', unique=True, blank=True, editable=False)

    def __str__(self):
        return f"{self.first_name} {self.last_name}"

    def get_absolute_url(self):
        return reverse('tracks:author', args=[self.slug])

    class Meta:
        verbose_name = 'Author'
        verbose_name_plural = 'Authors'


class Genre(Model):
    name = models.CharField('Genre', max_length=50, null=False)

    def __str__(self):
        return f"{self.name}"

    class Meta:
        verbose_name = 'Genre'
        verbose_name_plural = 'Genres'


class Track(Model):
    title = models.CharField('Title', max_length=100, null=False)
    description = models.TextField('Description', default='', max_length=1000, null=False)
    audio = models.FileField('Audio', upload_to='media/', blank=True)
    genre = models.ForeignKey(Genre, on_delete=models.SET_NULL, null=True)
    author = models.ForeignKey(Author, on_delete=models.SET_NULL, null=True)
    slug = AutoSlugField(populate_from='title', unique=True, db_index=True, editable=False, blank=True)
    pubdate = models.DateTimeField(auto_now_add=True, null=True, editable=False)
    pub_by = models.ForeignKey(User, on_delete=models.SET_NULL, blank=True, null=True)

    def __str__(self):
        return f"{self.title}"

    def get_absolute_url(self):
        return reverse('tracks:track', args=[self.slug])

    class Meta:
        verbose_name = 'Track'
        verbose_name_plural = 'Tracks'
        ordering = ['-pubdate']

accounts/forms.py
from django import forms
from tracks.models import Track
from .models import UserProfile


class TrackForm(forms.ModelForm):
    widgets = {
        'pub_by': forms.HiddenInput
    }

    class Meta:
        model = Track
        fields = ('title', 'description', 'audio', 'genre', 'author')


class ProfileForm(forms.ModelForm):
    widgets = {
        'User': forms.HiddenInput
    }

    class Meta:
        model = UserProfile
        fields = ('image', 'description')

accounts/views.py
from django.core.mail import send_mail
from django.contrib import messages
from django.shortcuts import get_object_or_404
from django.urls import reverse_lazy
from OpenMusic.settings import DEFAULT_FROM_EMAIL
from allauth.account.signals import user_signed_up
from django.dispatch import receiver
from django.views.generic import DetailView, CreateView
from tracks.models import Track
from .forms import TrackForm, ProfileForm
from .models import UserProfile
from django.views.generic.edit import FormMixin


class CustomSuccessMessageMixin:
    @property
    def success_msg(self):
        return False

    def form_valid(self, form):
        messages.success(self.request, self.success_msg)
        return super().form_valid(form)

    def get_success_url(self):
        return f'{self.success_url}?slug={self.object.slug}'


class UserProfileSearchView(DetailView):
    template_name = 'account/user_search.html'
    model = UserProfile

    def get_object(self, queryset=None):
        return UserProfile.objects.get(User__username=self.kwargs.get('name', None))

    def get_context_data(self, **kwargs):
        context = super(UserProfileSearchView, self).get_context_data()
        context['published'] = Track.objects.filter(pub_by__userprofile__id=self.object.id)
        return context


class UserProfileView(DetailView, CustomSuccessMessageMixin, FormMixin):
    model = UserProfile
    template_name = 'account/user_profile.html'
    form_class = ProfileForm
    success_msg = 'Successful saved.'

    def get_object(self, queryset=None):
        username = self.kwargs.get('name', None)
        if username:
            return UserProfile.objects.get(User=username)
        if UserProfile.objects.filter(User=self.request.user):
            return UserProfile.objects.get(User=self.request.user)
        else:
            return UserProfile.objects.create(User=self.request.user)

    def get_success_url(self):
        return reverse_lazy('profile')

    def post(self, request, *args, **kwargs):
        form = ProfileForm(request.POST, request.FILES)
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def form_valid(self, form):
        current_profile = UserProfile.objects.get(User=self.request.user)
        current_profile.description = form.cleaned_data['description']
        current_profile.image = form.cleaned_data['image']
        current_profile.save(force_update=True)
        return super().form_valid(form)


class TrackAddView(CreateView):
    model = Track
    form_class = TrackForm
    template_name = 'account/track_add.html'

    def form_valid(self, form):
        form.instance.pub_by = self.request.user
        return super(TrackAddView, self).form_valid(form)


@receiver(user_signed_up)
def user_signed_up(request, user, **kwargs):
    send_mail('Signup OpenMusic', 'Hi!\nThanks for signup!\nConfirm your email at next letter.\n OpenMusic.', DEFAULT_FROM_EMAIL, [user.email], fail_silently=True)

tracks/views.py
from django.shortcuts import get_object_or_404
from django.views.generic import DetailView, ListView, TemplateView, CreateView
from .models import Author, Track


class TrackListView(ListView):
    model = Track
    template_name = 'tracks/track_list.html'
    paginate_by = 5

    def get_queryset(self):
        genre = self.kwargs.get('genre', None)
        if genre:
            return Track.objects.filter(genre__name=genre)
        else:
            return Track.objects.all()


class TrackDetailView(DetailView):
    model = Track
    template_name = 'tracks/track_detail.html'

    def get_object(self, queryset=None):
        return get_object_or_404(Track, slug__iexact=self.kwargs['slug'])


class AuthorDetailView(DetailView):
    model = Author
    template_name = 'tracks/author_detail.html'

    def get_object(self, queryset=None):
        return get_object_or_404(Author, slug__iexact=self.kwargs['slug'])

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['Tracks'] = Track.objects.filter(author__slug=self.kwargs['slug'])
        return context


class MainView(TemplateView):
    template_name = 'index.html'

templates/index.html
{% extends 'template.html' %}
{% block content %}
{% endblock %}

templates/template.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <title>{% block heading %}Tracks{% endblock %}</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static "hrs.css" %}">
    <!-- JS, Popper.js, and jQuery -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    {% block head %}

    {% endblock %}

</head>
<body class="bg-dark">

<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a style="text-transform: uppercase" class="navbar-brand" href="{% url 'tracks:main' %}">OpenMusic</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" style="text-transform: uppercase" href="{% url 'tracks:tracks' %}">Tracks <span class="sr-only"></span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" style="text-transform: uppercase" href="#">Features</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" style="text-transform: uppercase" href="#">Pricing</a>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled" style="text-transform: uppercase" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
      </li>
        {% if user.is_authenticated %}
        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" data-toggle="dropdown" style="text-transform: uppercase" href="#">
                {% if user.socialaccount_set.all.0.provider %}
                    {{ user.socialaccount_set.all.0.extra_data.name }}
                {% else %}
                    {{ user }}
                    {% endif %}</a>
            <div class="dropdown-menu">
                <a class="dropdown-item" style="text-transform: uppercase" href="{% url 'account_logout' %}">Logout</a>
                <a class="dropdown-item" style="text-transform: uppercase" href="{% url 'profile' %}">Profile</a>
            </div>
        </li>
            {% else %}
            <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" data-toggle="dropdown" style="text-transform: uppercase" href="#">Account</a>
            <div class="dropdown-menu">
                <a class="dropdown-item" style="text-transform: uppercase" href="{% url 'account_login' %}">Login</a>
                <a class="dropdown-item" style="text-transform: uppercase" href="{% url 'account_signup' %}">Signup</a>
            </div>
        </li>
        {% endif %}


    </ul>
  </div>
</nav>
<div class="row text-light">
    <div class="col-sm-2 bg-dark">
        {% block leftsidebar %}

        {% endblock %}
    </div>
    <div class="col-lg-8 bg-dark">
        {% block content %}
        {% endblock %}
    {% if is_paginated %}
        <div class="pagination" style="justify-content: center;margin-bottom: 15px">
            <span class="page-links">
                {% if page_obj.has_previous %}
                    <a href="{{ request.path }}?page={{ page_obj.previous_page_number }}">Предыдущая</a>
                {% endif %}
                <span class="page-current">
                    Страница {{ page_obj.number }} из {{ page_obj.paginator.num_pages }}
                </span>
                {% if page_obj.has_next %}
                    <a href="{{ request.path }}?page={{ page_obj.next_page_number }}">Следующая</a>
                {% endif %}
            </span>
        </div>
    {% endif %}
    </div>
    <div class="col-sm-2 bg-dark">
        {% block rightsidebar %}
        {% endblock %}
    </div>
</div>

        <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
</body>
</html>

templates/tracks/author_detail.html
{% extends 'template.html' %}

{% block heading %}
{{ author.first_name }} {{ author.last_name }}
{% endblock %}
{% block content %}

    <h1 class="text-center">{{ author.first_name }} {{ author.last_name }}</h1>
    <p><strong>Description: </strong>{{ author.description }}</p>
    <h2 class="text-center">Author track list:</h2>
    {% for track in Tracks %}
        <h2 class="text-center"><a href="{{ track.get_absolute_url }}">{{ track.title }}</a></h2>
    {% endfor %}

{% endblock %}

templates/tracks/track_detail.html
{% extends 'template.html' %}
{% block heading %}{{ track.title }}{% endblock %}
{% block content %}

    <div class="container">
        <h2 class="center">{{ track.title }}</h2>
        <p><strong>Description: </strong>{{ track.description }}</p>
        <p><strong>Genre: </strong>{{ track.genre }}</p>
        <p><strong>Author: </strong><a href="{{ track.author.get_absolute_url }}">{{ track.author }}</a></p>
        <p><strong>Play: </strong>
            {% if track.audio %}<audio controls preload="metadata" id="track-med" src="{{ track.audio.url }}"></audio></p>{% endif %}
        <p><strong>Pubdate: </strong>{{ track.pubdate }}</p>
    </div>
{% endblock %}

templates/tracks/track_list.html
{% extends 'template.html' %}
{% load static %}
{% block heading %}Tracks{% endblock %}
{% block content %}
    {% for track in track_list %}
        <div class="container-fluid">
            <h2 class="center"><a href="{{ track.get_absolute_url }}">{{ track.title }}</a></h2>
            <p><strong>Description: </strong>{{ track.description }}</p>
            <p><strong>Genre: </strong><a href="{% url 'tracks:tracks' track.genre %}">{{ track.genre }}</a></p>
            <p><strong>Author: </strong>{{ track.author }}</p>
            <p><strong>Published by: </strong><a href="{% url 'profile' track.pub_by %}">{{ track.pub_by }}</a></p>
            {% if track.audio %}<audio id="track-med" preload="auto" src="{{ track.audio.url }}"></audio></p>{% endif %}
            <button onclick="play()">Preview</button>
        </div>
        <hr class="end-hr">
    {% endfor %}
        <script src={% static "audio_stopper.js" %}></script>
{% endblock %}